version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: pyspark
    ports:
      - "4040:4040"
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=sparky
    volumes:
      - ./data:/home/jovyan/work
